/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f72babb6-de5e-47f0-9455-7739768b8055",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2znjVYZnm",
    "aws_user_pools_web_client_id": "3tmbrvq1qpk0ic52mv7hq9k9ee",
    "oauth": {}
};


export default awsmobile;
